### ISSUE TITLE
Bot cannot throw out items on servers sometimes maybe all the time idk

### ISSUE THREAD

**Issue by drmcbride1** [gaucho-matrero/altoclef#300] opened 2022-09-21 23:41 UTC
## Steps to Reproduce (as best as you can)
play on a server
@gamer or something that causes the bot to get a full inventory
Maybe fps lag a bit? (not sure if lag causes this)
Have like more then 50 ping aswell maybe (again not sure)
get stuck on it trying to shuffle out worthless items.

## Expected Behavior
have it manage inventory corrrectly

## Actual Behavior (What lead to the bot getting permanently stuck)
it just shuffles 2 items in and out of the inventory
## Crashlogs and Screenshots (if applicable)

_(you may drag + drop text logs and images here, thanks GitHub)_

### Discord username (if you want updates)
Mafioso Landslide#3193
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by drmcbride1** [comment] 2022-09-21 23:42
Also I can manually fix it by opening the inventory and closing it again and the bot will throw the item out then.
It starts with no E menu open maybe thats the problem? not sure

**Comment by drmcbride1** [comment] 2022-09-21 23:43
Before I help it
![image](https://user-images.githubusercontent.com/114117540/191628758-69647740-8af6-480e-84cc-80766542089d.png)

When I press E
![image](https://user-images.githubusercontent.com/114117540/191628785-a4c3914d-1bfc-4beb-96b8-ed1a2e34a022.png)
Then after this when I press E again it drops it and goes along its journey

**Comment by JustaSqu1d** [comment] 2022-09-21 23:56
Duplicate of #276

**Comment by drmcbride1** [comment] 2022-09-22 00:30
> Duplicate of #276

yeah but I included a shit ton more info

**Comment by JamesGreen31** [comment] 2023-03-22 16:16
I will merge the issues

**Closed** 2023-03-22 16:17 UTC
Labels: major bug
