### ISSUE TITLE
2 Crafting Issues (Gamer Task)

### ISSUE THREAD

**Issue by TheGamerGerman** [gaucho-matrero/altoclef#229] opened 2022-03-23 09:20 UTC
## Steps to Reproduce (as best as you can)
1: Go into a new world do @gamer then wait until it needs to craft the first stuff it will get stuck.
2:Crafting Ender eyes with @gamer. Gets stuck 

## Expected Behavior
Should not get stuck while crafting
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_

**Comment by JamesGreen31** [comment] 2022-03-23 23:37
Began work on fixing this issue

**Comment by JamesGreen31** [comment] 2022-03-23 23:38
Can you supply a brief video or a screenshot? Currently, there is a known issue revolving around the crafting book where it will not be able to craft with your inventory open. Can you open your inventory when it gets stuck and see if that resolves it?

**Comment by TheGamerGerman** [comment] 2022-03-25 19:19
If it has the 1. issue opening the inv fixes it 2. issue cant be fix need to turn off alto clef and then craft bymyself

**Comment by JamesGreen31** [comment] 2022-03-25 19:23
Interesting. This indicates two seperate problems. Does (2) happen everytime?

**Comment by TheGamerGerman** [comment] 2022-03-25 22:57
yes it does

**Comment by JamesGreen31** [comment] 2022-03-26 04:20
Some major work was done on this issue, so I'm posting an update.

**cause:**

When altoclef has book crafting enabled, a bug was present that essentially made it impossible for altoclef to clear out "trash spots" in the 2x2 crafting menu. Essentially, the bot would have two items which both needed to be cleared and would endlessly swap between them in an attempt to remove the bad items. 

**fix:**

A task was created to ensure that the cursor slot is empty before it attempts to clear out the bad items. This ensures that it is able to actually remove them from the crafting grid instead of swapping between two bad items. 

**possibly related issues:**

This problem can occur anytime the bot has to remove a garbage item from a container. By ensuring the space in the cursor is available, any issue that was caused by the items failing to swap should be resolved. 

If you would like the technical details of the bug and resolution, please reach out to me on discord.

_expected release for fix:_

Currently, there are a few other issues similar to this that should be addressed before a PR is made. One such example is that items have a chance of getting stuck in the 2x2 crafting grid if the items were placed there immediately prior to the bot using a crafting table. Once I fix this issue, if there are no immediate problems that arise, I will publish a PR

**Comment by JamesGreen31** [comment] 2022-03-27 17:09
**Update**

We resolved the issue with blocks getting stuck in the 2x2 crafting grid. There are a few other problems with crafting that I am going to try and resolve before merging. There are a few times where it has difficulty placing a table as well as a few issues where it tries to click where it shouldn't click. If these are crafting related, I will fix them, otherwise they will be in a separate PR.

This PR will be for crafting fixes in general. Should make things a lot better.

I will post another update in a few days once I get that far.

**Comment by JamesGreen31** [comment] 2022-03-29 06:14
**Pull Request #233 opened and pending review from partner. Upon approval, this issue will resolve.**

Please note that the ender eye issue is not believed to be a crafting issue at this time, and will remain bugged until we re-work BeatMinecraft2. Crafting on the other hand should now work fine (and should even be faster).

No further development comments will be made in relation to this issue.

**Comment by TheGamerGerman** [comment] 2022-03-29 12:29
Thank you

**Comment by TheGamerGerman** [comment] 2022-03-29 12:39
Does not work
crafting cant get fixed with opening inv now

**Comment by Foxy6670** [comment] 2022-03-29 13:45
The pull request has not been merged yet. This can take a while.

**Comment by JamesGreen31** [comment] 2022-03-29 15:08
It will probably get merged by Sunday. You can always checkout the branch on my fork if you want it early. It's CraftingbookFixes

**Comment by JamesGreen31** [comment] 2022-04-01 03:26
Issues still not resolved.

**Comment by JamesGreen31** [comment] 2022-04-01 06:01
Final edits to the PR submitted. It should work, even if it sometimes looks a little janky

**Comment by JamesGreen31** [comment] 2022-04-01 15:03
Re-opened as PR has not been merged. It will close the issue itself.

**Comment by JamesGreen31** [comment] 2022-04-06 02:40
This issue is fixed

**Closed** 2022-04-06 02:40 UTC
Labels: major bug
