### ISSUE TITLE
Bot Gets Stuck In Water 

### ISSUE THREAD

**Issue by Toyota-Supra** [gaucho-matrero/altoclef#108] opened 2021-10-05 15:23 UTC
**_When the bot goes into any water source sometimes it gets stuck in that one block with it's head moving very fast._**

**Comment by adrisj7** [comment] 2021-10-05 21:33
Duplicate of https://github.com/gaucho-matrero/altoclef/issues/107

**Closed by adrisj7** 2021-10-05 21:33 UTC
Labels: duplicate
