### ISSUE TITLE
Crafting 16 pickaxes without all the items breaks altoclef

### ISSUE THREAD

**Issue by Dabaski** [gaucho-matrero/altoclef#274] opened 2022-05-25 06:59 UTC
## Steps to Reproduce (as best as you can)
@get diamond_pickaxe 16, crafting speed 0.2
## Expected Behavior
Get all the items and craft 16 pickaxes
## Actual Behavior (What lead to the bot getting permanently stuck)
Got some items but broke trying to craft them before it got all of the items
## Crashlogs and Screenshots (if applicable)
_(you may drag + drop text logs and images here, thanks GitHub)_
[croppedlog.log](https://github.com/gaucho-matrero/altoclef/files/8768649/croppedlog.log)
)
### Discord username (if you want updates)
Dabaski fro the discord server
### Developer Notes (leave this blank)

_Difficulty_: **__**
_Estimated Time Required_: **__**
Once development starts.

**Comment by JamesGreen31** [comment] 2022-05-25 16:52
This is a duplicate of issue 24, which is quite difficult to solve.

Some suggest putting items in chests, but altoclef has to be able to remember all this information. The way it is currently designed, it is not able to do this.

Because we are considering re-designing certain aspects of AC, this issue may not be addressed for some time.

**Closed by JamesGreen31** 2022-05-25 16:52 UTC
Labels: major bug, duplicate
